<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2889" started-at="2019-06-05T08:58:36Z" finished-at="2019-06-05T08:58:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2889" started-at="2019-06-05T08:58:36Z" finished-at="2019-06-05T08:58:39Z">
      <class name="kovair.JenkinsIntegration.JenkinsIntegrationExtentReport">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df]" name="BeforeTest" is-config="true" duration-ms="1777" started-at="2019-06-05T08:58:36Z" finished-at="2019-06-05T08:58:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="Test1()[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df]" name="Test1" duration-ms="22" started-at="2019-06-05T08:58:38Z" finished-at="2019-06-05T08:58:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df]" name="afterMethod" is-config="true" duration-ms="67" started-at="2019-06-05T08:58:38Z" finished-at="2019-06-05T08:58:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test1 status=SUCCESS method=JenkinsIntegrationExtentReport.Test1()[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="Test2()[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df]" name="Test2" duration-ms="5" started-at="2019-06-05T08:58:38Z" finished-at="2019-06-05T08:58:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at kovair.JenkinsIntegration.JenkinsIntegrationExtentReport.Test2(JenkinsIntegrationExtentReport.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df]" name="afterMethod" is-config="true" duration-ms="17" started-at="2019-06-05T08:58:38Z" finished-at="2019-06-05T08:58:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test2 status=FAILURE method=JenkinsIntegrationExtentReport.Test2()[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:kovair.JenkinsIntegration.JenkinsIntegrationExtentReport@4b9e13df]" name="AfterTest" is-config="true" duration-ms="873" started-at="2019-06-05T08:58:38Z" finished-at="2019-06-05T08:58:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- kovair.JenkinsIntegration.JenkinsIntegrationExtentReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
